name: build_turbo2

on:
  push:
    branches:
      - main
      
env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: build ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-18.04, macos-10.15, macos-11.0]

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - run: npm install
        working-directory: 'electron'

      - run: npx electron-build-env neon build
        working-directory: 'electron'
